version: "3"
services:
  project_my_shop_93:
    build: .
    ports:
     - "2529:2529"
    env_file:
      - "./.dev.env"
    volumes:
      - public-express-project_my_shop_93:/app/public
    depends_on:
      - db_my_shop_93
  db_my_shop_93:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=codifyer_database
      - MYSQL_DATABASE=db_my_shop_93
    volumes:
      - mysql-db-project_my_shop_93:/var/lib/mysql
    ports:
      - "3004:3306"
  phpmyadmin_my_shop_93:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_my_shop_93
    links:
      - db_my_shop_93
    environment:
      PMA_HOST: db_my_shop_93
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 5501:8090

volumes:
  mysql-db-project_my_shop_93:
  public-express-project_my_shop_93: